var emojidb = {
  "🐵": "Monkey Face",
  "🐺": "Wolf Face",
  "🐩": "Poodle",
  "🐶": "Dog Face",
  "🐒": "Monkey",
  "🐭": "Mouse Face",
  "🐘": "Elephant",
  "🐫": "Two-Hump Camel",
  "🐗": "Boar",
  "🐷": "Pig Face",
  "🐮": "Cow Face",
  "🐴": "Horse Face",
  "🐯": "Tiger Face",
  "🐱": "Cat Face",
  "🐧": "Penguin",
  "🐦": "Bird",
  "🐤": "Baby Chick",
  "🐣": "Hatching Chick",
  "🐔": "Chicken",
  "🐼": "Panda",
  "🐨": "Koala",
  "🐻": "Bear",
  "🐰": "Rabbit Face",
  "🐹": "Hamster",
  "🐞": "Lady Beetle",
  "🐝": "Honeybee",
  "🐜": "Ant",
  "🐛": "Bug",
  "🐌": "Snail",
  "🐙": "Octopus",
  "🐟": "Fish",
  "🐬": "Dolphin",
  "🐳": "Spouting Whale",
  "🐲": "Dragon Face",
  "🐍": "Snake",
  "🐢": "Turtle",
  "🐸": "Frog"
};

export default emojidb;
